### ISSUE TITLE
Determine if Site Issues

### ISSUE THREAD

**Issue by dabercro** [CMSCompOps/OSDroid#2]
Determine whether problematic workflows are caused by site issues or workflow configuration issues. Site issues are easier for P&R to make adjustments to running workflows.

  -- Feedback from CompOps weekly meeting

**Comment by phylsix** [comment]
right, this is going to be important piece. I feel supervised approach is easier and worthwhile as a first trial. Do you know where we can get information that a real site issue happened? @dabercro

**Comment by dabercro** [comment]
Ah, we did ask about this before. From an old email from Thong:

> If the failures are caused by the system (like file read error, condor glitch, etc.) then we will ACDC to try again with the hope that the system error is temporary. If the failures is intrinsic in the workflow (like wrong configuration, software issue, etc.) then ACDC won’t be able to fix it and we will just bypass and ask the submitters to fix the issues.

So, I think ACDC means generally site problems. Maybe @thongonary, @amaltaro, or @jenimal can point us to something else for training data too.

**Comment by phylsix** [comment]
Does name changing solve the issue? :)
- ACDC-ed --> site issue
- Resubmitted --> workflow issue

**Comment by dabercro** [comment]
Yeah, let's just do that for now until we learn something better.

**Comment by phylsix** [comment]
close for now, can be reopened in the future if we know something better.
