### ISSUE TITLE
transform the data storage as a db

### ISSUE THREAD

**Issue by phylsix** [CMSCompOps/OSDroid#4]
For the moment, the data source is saved as raw json files. For each request, the json file was loaded by python json module. As data keep accumulating, a more formal option, database, should take over. Could potentially gain some speed. I think python sqlite3 would be enough.

**Comment by dabercro** [comment]
After my experience with Sqlite3 on the old console, I would recommend going straight to MySQL instead. It's able to handle simultaneous users.

**Comment by phylsix** [comment]
cool, thanks for the suggestion! I will take a look at MySQL.
